### PR TITLE
use the same uuid for new PUBLISH messages

### PR DESCRIPTION
**Pull request by littleskunk**
Closes https://github.com/Storj/core/issues/486

### CODE REVIEW

**Comment by littleskunk** [comment]
Do I need random luck for the unit tests or is something wrong? Executed the unit tests local and 1 passed and 2 failed.

**Comment by bookchin** [comment]
@littleskunk yeah, the test suite needs a lot of work. i'm testing this PR manually right now.

**Comment by bookchin** [comment]
manual testing *does* appear that this breaks something - i'm looking into it

**Comment by bookchin** [comment]
okay, i was able to get this to work by modifying the tests. the problem here is that all we have here is an integration test, and quasar is a probabilistic algorithm. most of the time the tests work, but sometimes they fail. they need to be replaced with unit tests.

for now, i got this to work by lowering the number of nodes used in the integration test and spreading the nodes used to test publication receipt.

i will merge this pr and then push my test fixes.

**Comment by bookchin** [comment]
so, the issue with the tests is really that all the node ids get randomly generated. so the tests are always different. i've updated this to use a static selection of nodeIDs.

**Pull request merged**
